# 核心任务
- name: metabase
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
   - {role: role_common, tags: "role_common"}   
   - {role: role_cloud, tags: "role_cloud"}
   - {role: role_docker, tags: "role_docker"}
   - {role: role_mysql, tags: "role_mysql"}
   - {role: role_nginx, tags: "role_nginx"}
   - {role: metabase, tags: "metabase"}
   - {role: role_init, tags: "role_init"}
   - {role: role_preend, tags: "role_preend"}
   - {role: role_end, tags: "role_end"} 





    


                                                                                                    
